import type { Metadata } from "next";
import { BookOpenText, CircleDollarSign, Crown, UsersRound } from "lucide-react";

export const metadata: Metadata = { title: "Admin mẫu" };
const adminStats = [{ label: "Người học", value: "1.248", icon: UsersRound }, { label: "Tài khoản VIP", value: "186", icon: Crown }, { label: "Bài đã xuất bản", value: "149", icon: BookOpenText }, { label: "Doanh thu tháng", value: "18,6tr", icon: CircleDollarSign }];
const courseRows = [["办", "Văn phòng & hành chính", "24", "1.062", "Đang mở"], ["产", "Nhà máy & sản xuất", "20", "784", "Đang mở"], ["仓", "Kho vận & logistics", "22", "638", "Đang mở"], ["客", "Bán hàng & CSKH", "18", "—", "Bản nháp"]];

export default function AdminPage() {
  return <main className="admin-page"><div className="section-shell">
    <div className="admin-top"><div className="admin-title"><span>HanziWork Console</span><h1>Tổng quan vận hành</h1></div><span className="demo-badge">Dữ liệu minh họa · Chưa có xác thực</span></div>
    <section className="admin-stats" aria-label="Chỉ số tổng quan">{adminStats.map(({ label, value, icon: Icon }) => <article className="admin-stat" key={label}><span className="admin-stat-icon"><Icon size={20} /></span><div><strong>{value}</strong><span>{label}</span></div></article>)}</section>
    <div className="admin-grid">
      <section className="admin-panel"><div className="panel-heading"><h2>Quản lý lộ trình</h2><span>Cập nhật hôm nay</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Lộ trình</th><th>Bài học</th><th>Người học</th><th>Trạng thái</th></tr></thead><tbody>{courseRows.map((row) => <tr key={row[1]}><td><span className="table-course"><span className="table-mark">{row[0]}</span>{row[1]}</span></td><td>{row[2]}</td><td>{row[3]}</td><td><span className={`status ${row[4] === "Đang mở" ? "live" : "draft"}`}>{row[4]}</span></td></tr>)}</tbody></table></div></section>
      <section className="admin-panel"><div className="panel-heading"><h2>Quy trình nội dung</h2><span>6 mục chờ</span></div><div className="pipeline"><div className="pipeline-step"><span>01</span><div><strong>Soạn từ & tình huống</strong><span>Người biên soạn</span></div><strong>3 mục</strong></div><div className="pipeline-step"><span>02</span><div><strong>Kiểm tra tiếng Trung</strong><span>Người duyệt nội dung</span></div><strong>2 mục</strong></div><div className="pipeline-step"><span>03</span><div><strong>Xem trước bài học</strong><span>Quản trị viên</span></div><strong>1 mục</strong></div><div className="pipeline-step"><span>04</span><div><strong>Xuất bản</strong><span>Tự động ghi phiên bản</span></div><strong>Sẵn sàng</strong></div></div></section>
    </div>
    <div className="admin-lower"><section className="admin-panel"><div className="panel-heading"><h2>Lượt học 7 ngày</h2><span>+18% so với tuần trước</span></div><div className="bar-chart" aria-label="Biểu đồ lượt học theo ngày">{[42, 66, 53, 78, 62, 90, 72].map((height, index) => <div className="bar-column" key={index}><div className="bar" style={{ height: `${height}%` }} /><span>T{index + 2}</span></div>)}</div></section><section className="admin-panel"><div className="panel-heading"><h2>Hoạt động gần đây</h2><span>Tự động cập nhật</span></div><div className="activity-list"><div className="activity-item"><i className="activity-dot" /><div><p>Giao dịch HW260731-018 đã kích hoạt VIP 6 tháng</p><span>8 phút trước</span></div></div><div className="activity-item"><i className="activity-dot" /><div><p>Bài “Theo dõi tiến độ” được cập nhật phiên bản 1.2</p><span>32 phút trước</span></div></div><div className="activity-item"><i className="activity-dot" /><div><p>12 từ mới đang chờ kiểm tra tiếng Trung</p><span>1 giờ trước</span></div></div></div></section></div>
  </div></main>;
}
