import type { Metadata } from "next";
import { AlertCircle, Check, Crown, QrCode } from "lucide-react";

export const metadata: Metadata = { title: "Gói HanziWork VIP" };
const plans = [
  { name: "1 tháng", price: "79.000đ", description: "Phù hợp để trải nghiệm trọn vẹn một lộ trình.", features: ["Mở toàn bộ bài học", "Luyện tập không giới hạn", "Theo dõi tiến độ"], featured: false },
  { name: "6 tháng", price: "329.000đ", description: "Lựa chọn cân bằng cho người học đều đặn.", features: ["Mọi quyền lợi VIP", "Tất cả 7 lộ trình", "Ôn theo từ làm sai", "Tiết kiệm hơn gói tháng"], featured: true },
  { name: "12 tháng", price: "549.000đ", description: "Dành cho mục tiêu học dài hạn và nhiều ngành.", features: ["Mọi quyền lợi VIP", "Nội dung mới trong kỳ", "Duy trì lịch sử học", "Chi phí theo tháng tốt nhất"], featured: false },
];

export default function VipPage() {
  return <main>
    <section className="section-shell vip-hero"><div className="eyebrow"><Crown size={16} /> HanziWork VIP</div><h1>Mở khóa việc học, không khóa bạn vào lộ trình cứng.</h1><p>Học mọi ngành bạn quan tâm, xem lại không giới hạn và luyện đúng những từ còn yếu. Giá dưới đây là đề xuất cho prototype và có thể chỉnh trước khi bán thật.</p></section>
    <section className="section-shell pricing-grid" aria-label="Các gói VIP">{plans.map((plan) => <article className={`price-card ${plan.featured ? "featured" : ""}`} key={plan.name}>{plan.featured && <span className="price-badge">Được chọn nhiều</span>}<span className="price-name">VIP {plan.name}</span><div className="price"><strong>{plan.price}</strong><span>/ gói</span></div><p className="price-description">{plan.description}</p><ul className="feature-list">{plan.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul><a className={`button button-full ${plan.featured ? "button-light" : "button-primary"}`} href="#quy-trinh">Xem quy trình mua</a></article>)}</section>
    <section className="section-shell vip-flow" id="quy-trinh"><h2>Quy trình mua VIP dự kiến</h2><div className="flow-grid"><article className="flow-step"><span>01</span><h3>Đăng nhập</h3><p>Người học cần có tài khoản để hệ thống biết VIP thuộc về ai.</p></article><article className="flow-step"><span>02</span><h3>Chọn gói</h3><p>Hiển thị rõ thời hạn, giá bán và quyền lợi trước khi thanh toán.</p></article><article className="flow-step"><span>03</span><h3>Quét QR SePay</h3><p>Mỗi đơn có mã nội dung riêng để đối soát giao dịch tự động.</p></article><article className="flow-step"><span>04</span><h3>Kích hoạt VIP</h3><p>Webhook xác nhận đúng số tiền rồi mới mở khóa và ghi lịch sử.</p></article></div><div className="prototype-note"><QrCode size={19} /><span>Bản prototype chưa nhận tiền thật và chưa kết nối SePay. Khi triển khai, tài khoản nhận tiền nên thuộc chủ thể kinh doanh đã đăng ký thay vì tài khoản cá nhân của một nhân viên.</span></div></section>
    <section className="section-shell policy-section" id="chinh-sach"><span className="section-kicker">Minh bạch trước khi bán</span><h2>Chính sách VIP bản đề xuất</h2><div className="policy-grid"><article className="policy-card"><h3>Kích hoạt</h3><p>VIP được kích hoạt sau khi hệ thống xác nhận thanh toán thành công. Thời hạn tính từ thời điểm kích hoạt.</p></article><article className="policy-card"><h3>Hoàn tiền</h3><p>Tiếp nhận yêu cầu nếu thanh toán trùng, bị trừ tiền nhưng không kích hoạt, hoặc lỗi do hệ thống chưa được xử lý.</p></article><article className="policy-card"><h3>Tài khoản & dữ liệu</h3><p>Mỗi gói gắn với một tài khoản. Không công khai dữ liệu học tập và cần có cơ chế đổi, xóa dữ liệu theo yêu cầu hợp lệ.</p></article></div><div className="prototype-note"><AlertCircle size={19} /><span>Nội dung này là khung sản phẩm, chưa thay thế điều khoản pháp lý chính thức. Trước ngày mở bán cần hoàn thiện thông tin chủ sở hữu, chính sách bảo mật, điều khoản sử dụng, hoàn tiền và thủ tục thương mại điện tử phù hợp.</span></div></section>
  </main>;
}
