import type { Metadata } from "next";
import { AlertCircle, Check, Crown, Route } from "lucide-react";
import { LearnerPageHeader } from "@/components/learner-page-header";

export const metadata: Metadata = { title: "Gói HanziWork VIP" };
const plans = [
  { name: "Học thử", price: "0đ", unit: "", description: "Học module nền tảng của cả bảy môi trường trước khi chọn lộ trình.", features: ["42 bài nền tảng", "252 từ cốt lõi", "7 bài kiểm tra module", "Ôn tập không cần thanh toán"], featured: false, href: "/courses", cta: "Chọn lộ trình", disabled: false },
  { name: "Trọn lộ trình Văn phòng", price: "Giá beta", unit: "mua một lần", description: "Mở khóa một sản phẩm hữu hạn, không buộc người học trả theo tháng.", features: ["Đủ 24 bài và 4 module", "18 bài chuyên sâu", "144 từ dùng trong công việc", "Ôn ưu tiên từ yếu", "Thử thách mới mỗi tuần"], featured: true, href: "#moc-mo-ban", cta: "Xem mốc mở bán", disabled: false },
  { name: "Trọn lộ trình Nhà máy", price: "Giá beta", unit: "mua một lần", description: "Tập trung vào giao tiếp an toàn, vận hành, chất lượng và bàn giao ca.", features: ["Đủ 24 bài và 4 module", "18 bài chuyên sâu", "144 từ dùng tại xưởng", "4 bài kiểm tra", "Thử thách công việc hằng tuần"], featured: false, href: "#moc-mo-ban", cta: "Xem mốc mở bán", disabled: false },
  { name: "Trọn lộ trình Kho vận", price: "Giá beta", unit: "mua một lần", description: "Tập trung vào nhập kho, tồn kho, soạn xuất, giao nhận và xử lý chênh lệch.", features: ["Đủ 24 bài và 4 module", "18 bài chuyên sâu", "144 từ kho vận", "4 bài kiểm tra", "Thử thách tình huống hằng tuần"], featured: false, href: "#moc-mo-ban", cta: "Xem mốc mở bán", disabled: false },
  { name: "Trọn lộ trình Bán hàng", price: "Giá beta", unit: "mua một lần", description: "Tập trung vào tư vấn nhu cầu, báo giá, theo dõi đơn và chăm sóc khách sau bán.", features: ["Đủ 24 bài và 4 module", "18 bài chuyên sâu", "144 từ bán hàng", "4 bài kiểm tra", "Thử thách tình huống hằng tuần"], featured: false, href: "#moc-mo-ban", cta: "Xem mốc mở bán", disabled: false },
  { name: "Trọn lộ trình Nhà hàng", price: "Giá beta", unit: "mua một lần", description: "Tập trung vào đón khách, gọi món, phục vụ tại bàn, thanh toán và phản hồi.", features: ["Đủ 24 bài và 4 module", "18 bài chuyên sâu", "144 từ nhà hàng", "4 bài kiểm tra", "Thử thách tình huống hằng tuần"], featured: false, href: "#moc-mo-ban", cta: "Xem mốc mở bán", disabled: false },
  { name: "Trọn lộ trình Thương mại điện tử", price: "Giá beta", unit: "mua một lần", description: "Tập trung vào gian hàng, nguồn hàng, thực hiện đơn, hậu mãi và tối ưu dữ liệu.", features: ["Đủ 24 bài và 4 module", "18 bài chuyên sâu", "144 từ thương mại điện tử", "4 bài kiểm tra", "Thử thách vận hành hằng tuần"], featured: false, href: "#moc-mo-ban", cta: "Xem mốc mở bán", disabled: false },
  { name: "Trọn lộ trình Giao tiếp cốt lõi", price: "Giá beta", unit: "mua một lần", description: "Tập trung vào nghe hiểu, nhận việc, phối hợp, báo vấn đề và giao tiếp đa kênh.", features: ["Đủ 24 bài và 4 module", "18 bài chuyên sâu", "144 từ nền tảng công việc", "4 bài kiểm tra", "Thử thách giao tiếp hằng tuần"], featured: false, href: "#moc-mo-ban", cta: "Xem mốc mở bán", disabled: false },
  { name: "VIP thư viện", price: "Sắp mở", unit: "", description: "Chỉ mở bán sau khi bảy lộ trình được duyệt ngôn ngữ và chứng minh có người học quay lại.", features: ["168 bài thuộc 7 chuyên ngành", "1.008 từ chủ động", "Kho ca làm mở rộng", "Lịch sử học dài hạn"], featured: false, href: "#moc-mo-ban", cta: "Chưa mở bán", disabled: true },
];

export default function VipPage() {
  return <main>
    <section className="section-shell learner-page-header-shell vip-page-header"><LearnerPageHeader
      description="HanziWork mở khóa từng lộ trình đã hoàn thiện. Bảy lộ trình hiện đã có đủ 24 bài; mua một lần theo nhu cầu vẫn là lựa chọn chính."
      eyebrow="Quyền lợi học tập"
      eyebrowIcon={Crown}
      meta={<><span><Route size={16} /><strong>07</strong> lộ trình chuyên ngành</span><span><Crown size={16} />Mua một lần theo nhu cầu</span></>}
      title="Chỉ trả tiền cho lộ trình bạn thật sự cần."
    /></section>
    <section className="section-shell pricing-grid" aria-label="Các lựa chọn học">{plans.map((plan) => <article className={`price-card ${plan.featured ? "featured" : ""}`} key={plan.name}>{plan.featured ? <span className="price-badge">Phù hợp giai đoạn hiện tại</span> : null}<span className="price-name">{plan.name}</span><div className="price"><strong>{plan.price}</strong>{plan.unit ? <span>/ {plan.unit}</span> : null}</div><p className="price-description">{plan.description}</p><ul className="feature-list">{plan.features.map((feature) => <li key={feature}><Check size={15} />{feature}</li>)}</ul>{plan.disabled ? <span className="button button-full button-disabled" aria-disabled="true">{plan.cta}</span> : <a className={`button button-full ${plan.featured ? "button-light" : "button-primary"}`} href={plan.href}>{plan.cta}</a>}</article>)}</section>
    <section className="section-shell vip-flow" id="moc-mo-ban"><h2>Mốc cần đạt trước khi nhận tiền</h2><div className="flow-grid"><article className="flow-step"><span>01</span><h3>Đủ chiều sâu</h3><p>Mỗi lộ trình có 24 bài thật, 4 module, 4 bài kiểm tra và kho từ được ôn theo lịch.</p></article><article className="flow-step"><span>02</span><h3>Duyệt ngôn ngữ</h3><p>Toàn bộ tiếng Trung, pinyin và ngữ cảnh cần được biên tập viên rà lại; các lộ trình nghiệp vụ cần chuyên gia kiểm tra thêm thuật ngữ, chứng từ, chính sách và an toàn.</p></article><article className="flow-step"><span>03</span><h3>Chạy beta</h3><p>Đo tỷ lệ hoàn thành, số ngày quay lại và mức sử dụng ôn tập riêng cho từng lộ trình trước khi chốt giá.</p></article><article className="flow-step"><span>04</span><h3>Mở khóa minh bạch</h3><p>Chỉ thu tiền cho lộ trình người học chọn; chuyên ngành tương lai luôn ghi rõ “đang biên soạn”.</p></article></div><div className="prototype-note"><Route size={19} /><span>Khung này chưa nhận tiền thật. Bảy lộ trình cần hoàn tất duyệt nội dung và beta trước khi chốt giá mua một lần hoặc mở VIP thư viện.</span></div></section>
    <section className="section-shell policy-section" id="chinh-sach"><span className="section-kicker">Minh bạch trước khi bán</span><h2>Chính sách VIP bản đề xuất</h2><div className="policy-grid"><article className="policy-card"><h3>Kích hoạt</h3><p>VIP được kích hoạt sau khi hệ thống xác nhận thanh toán thành công. Thời hạn tính từ thời điểm kích hoạt.</p></article><article className="policy-card"><h3>Hoàn tiền</h3><p>Tiếp nhận yêu cầu nếu thanh toán trùng, bị trừ tiền nhưng không kích hoạt, hoặc lỗi do hệ thống chưa được xử lý.</p></article><article className="policy-card"><h3>Tài khoản & dữ liệu</h3><p>Mỗi gói gắn với một tài khoản. Không công khai dữ liệu học tập và cần có cơ chế đổi, xóa dữ liệu theo yêu cầu hợp lệ.</p></article></div><div className="prototype-note"><AlertCircle size={19} /><span>Nội dung này là khung sản phẩm, chưa thay thế điều khoản pháp lý chính thức. Trước ngày mở bán cần hoàn thiện thông tin chủ sở hữu, chính sách bảo mật, điều khoản sử dụng, hoàn tiền và thủ tục thương mại điện tử phù hợp.</span></div></section>
  </main>;
}
