import type { LessonChallenge, Vocabulary } from "./content-types.ts";
import type { OfficeLessonSeed, OfficeModuleSeed } from "./office-course-seed.ts";

function word(
  slug: string,
  hanzi: string,
  pinyin: string,
  meaning: string,
  example: string,
  translation: string,
): Vocabulary {
  return { slug, hanzi, pinyin, meaning, example, translation, audioUrl: null };
}

export const foundationChallenge: LessonChallenge = {
  title: "Kiểm tra nền tảng văn phòng",
  description: "Hoàn thành 3/4 câu để xác nhận bạn đã sẵn sàng chuyển sang các tình huống phối hợp công việc.",
  passScore: 3,
  questions: [
    {
      prompt: "Bạn muốn hỏi lịch sự hạn chót của nhiệm vụ. Câu nào phù hợp nhất?",
      options: ["请问，截止日期是什么时候？", "你为什么还没做？", "这个工作不重要。"],
      correctOption: 0,
      explanation: "请问 làm câu hỏi mềm và lịch sự hơn; 截止日期 là hạn chót.",
    },
    {
      prompt: "Cụm nào dùng để báo công việc đang được thực hiện?",
      options: ["已完成", "进行中", "改期"],
      correctOption: 1,
      explanation: "进行中 nghĩa là đang tiến hành; 已完成 là đã hoàn thành.",
    },
    {
      prompt: "Khi gửi báo cáo qua email, câu nào nhắc người nhận xem tệp đính kèm?",
      options: ["请查看附件。", "请安排会议。", "请介绍自己。"],
      correctOption: 0,
      explanation: "附件 là tệp đính kèm, vì vậy 请查看附件 là mẫu phù hợp.",
    },
    {
      prompt: "Bạn gặp lỗi khi xuất tệp và muốn nhờ đồng nghiệp xem giúp. Câu nào tự nhiên nhất?",
      options: ["你必须解决。", "你可以帮忙看看吗？", "这个文件没问题。"],
      correctOption: 1,
      explanation: "你可以帮忙看看吗？ là lời nhờ hỗ trợ nhẹ nhàng và phù hợp giữa đồng nghiệp.",
    },
  ],
};

export const officeExpansionModules: OfficeModuleSeed[] = [
  {
    slug: "phoi-hop-va-giai-quyet-cong-viec",
    title: "Phối hợp & giải quyết công việc",
    description: "Làm rõ yêu cầu, bàn giao, xử lý thay đổi và đưa ra phản hồi trong công việc hằng ngày.",
  },
  {
    slug: "hop-bao-cao-va-du-an",
    title: "Họp, báo cáo & dự án",
    description: "Tham gia cuộc họp, trình bày số liệu, ghi nhận quyết định và quản lý rủi ro dự án.",
  },
  {
    slug: "hanh-chinh-va-giao-tiep-nang-cao",
    title: "Hành chính & giao tiếp nâng cao",
    description: "Xử lý thủ tục, tiếp khách, điện thoại và những tình huống dễ gây hiểu lầm tại công sở.",
  },
];

export const officeExpansionLessons: OfficeLessonSeed[] = [
  {
    moduleSlug: "phoi-hop-va-giai-quyet-cong-viec",
    slug: "lam-ro-yeu-cau-cong-viec",
    title: "Làm rõ yêu cầu công việc",
    summary: "Hỏi lại phạm vi, tiêu chuẩn và ví dụ để tránh bắt đầu công việc khi yêu cầu còn mơ hồ.",
    situation: "Nhận yêu cầu chưa đầy đủ",
    estimatedMinutes: 12,
    isFree: false,
    vocabulary: [
      word("yaoqiu", "要求", "yāoqiú", "yêu cầu", "请说明一下具体要求。", "Vui lòng giải thích yêu cầu cụ thể."),
      word("juti", "具体", "jùtǐ", "cụ thể", "我们需要一个具体的计划。", "Chúng ta cần một kế hoạch cụ thể."),
      word("shuoming", "说明", "shuōmíng", "giải thích, trình bày", "请说明这个表格怎么填写。", "Vui lòng giải thích cách điền biểu mẫu này."),
      word("fanwei", "范围", "fànwéi", "phạm vi", "这项工作不在我的负责范围内。", "Việc này không thuộc phạm vi phụ trách của tôi."),
      word("biaozhun", "标准", "biāozhǔn", "tiêu chuẩn", "文件格式要符合公司的标准。", "Định dạng tài liệu phải phù hợp tiêu chuẩn công ty."),
      word("juli", "举例", "jǔlì", "nêu ví dụ", "您可以举例说明吗？", "Anh/chị có thể nêu ví dụ để giải thích không?"),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "这份客户资料今天整理一下。", pinyin: "Zhè fèn kèhù zīliào jīntiān zhěnglǐ yíxià.", translation: "Hôm nay hãy sắp xếp lại bộ tài liệu khách hàng này." },
        { speaker: "B", hanzi: "好的，请问具体要求是什么？", pinyin: "Hǎo de, qǐngwèn jùtǐ yāoqiú shì shénme?", translation: "Vâng, xin hỏi yêu cầu cụ thể là gì?" },
        { speaker: "A", hanzi: "请按地区分类，格式要符合这个标准。", pinyin: "Qǐng àn dìqū fēnlèi, géshì yào fúhé zhège biāozhǔn.", translation: "Hãy phân loại theo khu vực và dùng định dạng theo tiêu chuẩn này." },
        { speaker: "B", hanzi: "明白了，您可以再举一个例子吗？", pinyin: "Míngbai le, nín kěyǐ zài jǔ yí ge lìzi ma?", translation: "Tôi hiểu rồi, anh/chị có thể cho thêm một ví dụ không?" },
      ],
      notes: [
        { title: "Hỏi phần chưa rõ", pattern: "请问具体要求是什么？", explanation: "Dùng khi yêu cầu mới chỉ nói mục tiêu chung. Hỏi rõ trước khi làm giúp giảm sửa lại về sau." },
        { title: "Xin ví dụ", pattern: "您可以举例说明吗？", explanation: "Mẫu lịch sự để xin một trường hợp minh họa khi tiêu chuẩn hoặc phạm vi còn trừu tượng." },
      ],
    },
  },
  {
    moduleSlug: "phoi-hop-va-giai-quyet-cong-viec",
    slug: "ban-giao-cong-viec",
    title: "Bàn giao công việc",
    summary: "Chuyển giao tài liệu, quyền truy cập và những lưu ý quan trọng cho người tiếp nhận.",
    situation: "Bàn giao trước khi nghỉ phép",
    estimatedMinutes: 12,
    isFree: false,
    vocabulary: [
      word("jiaojie", "交接", "jiāojiē", "bàn giao", "我们下午进行工作交接。", "Chiều nay chúng ta tiến hành bàn giao công việc."),
      word("jieshou", "接手", "jiēshǒu", "tiếp nhận", "下周由小李接手这个项目。", "Tuần sau Tiểu Lý sẽ tiếp nhận dự án này."),
      word("ziliao", "资料", "zīliào", "tài liệu, dữ liệu", "相关资料都在这个文件夹里。", "Tài liệu liên quan đều nằm trong thư mục này."),
      word("quanxian", "权限", "quánxiàn", "quyền truy cập", "我已经为你开通系统权限。", "Tôi đã mở quyền truy cập hệ thống cho bạn."),
      word("fuzeren", "负责人", "fùzérén", "người phụ trách", "有问题可以联系项目负责人。", "Nếu có vấn đề, bạn có thể liên hệ người phụ trách dự án."),
      word("zhuyi-shixiang", "注意事项", "zhùyì shìxiàng", "điều cần lưu ý", "请先看一下交接的注意事项。", "Hãy xem trước các điều cần lưu ý khi bàn giao."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "我下周请假，项目需要交接给你。", pinyin: "Wǒ xià zhōu qǐngjià, xiàngmù xūyào jiāojiē gěi nǐ.", translation: "Tuần sau tôi nghỉ phép nên cần bàn giao dự án cho bạn." },
        { speaker: "B", hanzi: "好的，相关资料都在哪里？", pinyin: "Hǎo de, xiāngguān zīliào dōu zài nǎli?", translation: "Được, toàn bộ tài liệu liên quan ở đâu?" },
        { speaker: "A", hanzi: "都在共享文件夹里，系统权限也开通了。", pinyin: "Dōu zài gòngxiǎng wénjiànjiā lǐ, xìtǒng quánxiàn yě kāitōng le.", translation: "Tất cả ở thư mục dùng chung, quyền hệ thống cũng đã được mở." },
        { speaker: "B", hanzi: "明白，还有什么注意事项吗？", pinyin: "Míngbai, hái yǒu shénme zhùyì shìxiàng ma?", translation: "Tôi hiểu rồi, còn điều gì cần lưu ý không?" },
      ],
      notes: [
        { title: "Thông báo bàn giao", pattern: "需要交接给……", explanation: "Dùng để nói rõ người tiếp nhận. Có thể đặt tên công việc hoặc dự án trước 需要." },
        { title: "Kiểm tra thông tin còn thiếu", pattern: "还有什么注意事项吗？", explanation: "Câu hỏi giúp người nhận chủ động tìm những rủi ro hoặc ngoại lệ chưa được ghi trong tài liệu." },
      ],
    },
  },
  {
    moduleSlug: "phoi-hop-va-giai-quyet-cong-viec",
    slug: "xu-ly-thay-doi-uu-tien",
    title: "Xử lý thay đổi ưu tiên",
    summary: "Xác nhận việc khẩn cấp, điều chỉnh thứ tự xử lý và làm rõ ảnh hưởng đến kế hoạch cũ.",
    situation: "Có nhiệm vụ khẩn chen ngang",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("youxianji", "优先级", "yōuxiānjí", "mức độ ưu tiên", "这个任务的优先级最高。", "Nhiệm vụ này có mức ưu tiên cao nhất."),
      word("tiaozheng", "调整", "tiáozhěng", "điều chỉnh", "我们需要调整工作计划。", "Chúng ta cần điều chỉnh kế hoạch công việc."),
      word("jinji", "紧急", "jǐnjí", "khẩn cấp", "客户有一个紧急需求。", "Khách hàng có một yêu cầu khẩn cấp."),
      word("zanting", "暂停", "zàntíng", "tạm dừng", "请先暂停现在的任务。", "Hãy tạm dừng nhiệm vụ hiện tại."),
      word("chongxin-anpai", "重新安排", "chóngxīn ānpái", "sắp xếp lại", "我会重新安排今天的工作。", "Tôi sẽ sắp xếp lại công việc hôm nay."),
      word("yingxiang", "影响", "yǐngxiǎng", "ảnh hưởng", "这个变化会影响原来的进度。", "Thay đổi này sẽ ảnh hưởng tiến độ ban đầu."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "客户刚发来一个紧急需求。", pinyin: "Kèhù gāng fā lái yí ge jǐnjí xūqiú.", translation: "Khách hàng vừa gửi một yêu cầu khẩn cấp." },
        { speaker: "B", hanzi: "需要提高这个任务的优先级吗？", pinyin: "Xūyào tígāo zhège rènwu de yōuxiānjí ma?", translation: "Có cần nâng mức ưu tiên của nhiệm vụ này không?" },
        { speaker: "A", hanzi: "是的，请先暂停原来的工作。", pinyin: "Shì de, qǐng xiān zàntíng yuánlái de gōngzuò.", translation: "Có, hãy tạm dừng công việc ban đầu trước." },
        { speaker: "B", hanzi: "这样会影响进度，我重新安排后向您确认。", pinyin: "Zhèyàng huì yǐngxiǎng jìndù, wǒ chóngxīn ānpái hòu xiàng nín quèrèn.", translation: "Việc này sẽ ảnh hưởng tiến độ; tôi sẽ sắp xếp lại rồi xác nhận với anh/chị." },
      ],
      notes: [
        { title: "Xác nhận mức ưu tiên", pattern: "需要提高……的优先级吗？", explanation: "Giúp tránh tự ý đổi thứ tự công việc khi yêu cầu khẩn chưa được người phụ trách xác nhận." },
        { title: "Nêu ảnh hưởng", pattern: "这样会影响……", explanation: "Nói rõ tác động trước khi nhận việc mới giúp quản lý cân đối kỳ vọng và nguồn lực." },
      ],
    },
  },
  {
    moduleSlug: "phoi-hop-va-giai-quyet-cong-viec",
    slug: "bao-tre-va-xin-gia-han",
    title: "Báo trễ và xin gia hạn",
    summary: "Thông báo sớm nguyên nhân, thời gian dự kiến và phương án bù khi không thể giữ hạn cũ.",
    situation: "Không kịp hoàn thành đúng hạn",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("yanqi", "延期", "yánqī", "gia hạn, hoãn", "项目需要延期两天。", "Dự án cần gia hạn hai ngày."),
      word("yuanyin", "原因", "yuányīn", "nguyên nhân", "请说明延期的原因。", "Vui lòng giải thích nguyên nhân trì hoãn."),
      word("yuji", "预计", "yùjì", "dự kiến", "预计明天下午完成。", "Dự kiến hoàn thành vào chiều mai."),
      word("yanchang", "延长", "yáncháng", "kéo dài", "可以把期限延长一天吗？", "Có thể kéo dài thời hạn thêm một ngày không?"),
      word("jinkuai", "尽快", "jǐnkuài", "sớm nhất có thể", "我们会尽快处理。", "Chúng tôi sẽ xử lý sớm nhất có thể."),
      word("bujiu", "补救", "bǔjiù", "khắc phục, bù đắp", "团队正在制定补救方案。", "Nhóm đang xây dựng phương án khắc phục."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "报告今天可以完成吗？", pinyin: "Bàogào jīntiān kěyǐ wánchéng ma?", translation: "Hôm nay báo cáo có thể hoàn thành không?" },
        { speaker: "B", hanzi: "很抱歉，因为数据有问题，可能需要延期。", pinyin: "Hěn bàoqiàn, yīnwèi shùjù yǒu wèntí, kěnéng xūyào yánqī.", translation: "Rất xin lỗi, do dữ liệu có vấn đề nên có thể cần gia hạn." },
        { speaker: "A", hanzi: "预计什么时候可以完成？", pinyin: "Yùjì shénme shíhou kěyǐ wánchéng?", translation: "Dự kiến khi nào có thể hoàn thành?" },
        { speaker: "B", hanzi: "预计明天下午完成，我们会尽快补救。", pinyin: "Yùjì míngtiān xiàwǔ wánchéng, wǒmen huì jǐnkuài bǔjiù.", translation: "Dự kiến chiều mai hoàn thành; chúng tôi sẽ khắc phục sớm nhất có thể." },
      ],
      notes: [
        { title: "Báo trễ có trách nhiệm", pattern: "因为……，可能需要延期", explanation: "Nêu nguyên nhân ngắn gọn, sau đó đưa ngay mốc dự kiến mới thay vì chỉ thông báo không kịp." },
        { title: "Đưa thời gian mới", pattern: "预计……完成", explanation: "预计 thể hiện đây là mốc dự kiến. Chỉ đưa mốc mà bạn đã cân nhắc và có khả năng giữ được." },
      ],
    },
  },
  {
    moduleSlug: "phoi-hop-va-giai-quyet-cong-viec",
    slug: "dua-ra-phan-hoi-va-de-xuat",
    title: "Đưa ra phản hồi và đề xuất",
    summary: "Góp ý vào kế hoạch bằng cách nêu điểm tốt, rủi ro và phương án cải thiện có thể thực hiện.",
    situation: "Đánh giá một phương án mới",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("fankui", "反馈", "fǎnkuì", "phản hồi", "谢谢你的反馈。", "Cảm ơn phản hồi của bạn."),
      word("jianyi", "建议", "jiànyì", "đề xuất, góp ý", "我建议先做一个小测试。", "Tôi đề xuất làm một thử nghiệm nhỏ trước."),
      word("gaijin", "改进", "gǎijìn", "cải thiện", "这个流程还有改进空间。", "Quy trình này vẫn còn chỗ để cải thiện."),
      word("kexing", "可行", "kěxíng", "khả thi", "这个方案在时间上可行。", "Phương án này khả thi về mặt thời gian."),
      word("youdian", "优点", "yōudiǎn", "ưu điểm", "这个方法的优点是速度快。", "Ưu điểm của phương pháp này là nhanh."),
      word("fangan-fengxian", "方案风险", "fāng'àn fēngxiǎn", "rủi ro của phương án", "我们需要评估方案风险。", "Chúng ta cần đánh giá rủi ro của phương án."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "你觉得这个新流程怎么样？", pinyin: "Nǐ juéde zhège xīn liúchéng zěnmeyàng?", translation: "Bạn thấy quy trình mới này thế nào?" },
        { speaker: "B", hanzi: "优点是速度快，但方案风险还没有评估。", pinyin: "Yōudiǎn shì sùdù kuài, dàn fāng'àn fēngxiǎn hái méiyǒu pínggū.", translation: "Ưu điểm là nhanh, nhưng rủi ro phương án chưa được đánh giá." },
        { speaker: "A", hanzi: "你有什么改进建议？", pinyin: "Nǐ yǒu shénme gǎijìn jiànyì?", translation: "Bạn có đề xuất cải thiện nào không?" },
        { speaker: "B", hanzi: "我建议先做一个小测试，确认可行以后再使用。", pinyin: "Wǒ jiànyì xiān zuò yí ge xiǎo cèshì, quèrèn kěxíng yǐhòu zài shǐyòng.", translation: "Tôi đề xuất thử nhỏ trước, xác nhận khả thi rồi mới áp dụng." },
      ],
      notes: [
        { title: "Góp ý cân bằng", pattern: "优点是……，但……", explanation: "Nêu điểm tốt trước rồi mới nói rủi ro giúp phản hồi rõ ràng mà không tạo cảm giác phủ nhận toàn bộ phương án." },
        { title: "Đưa đề xuất", pattern: "我建议先……", explanation: "先 nhấn mạnh bước thử nghiệm hoặc kiểm tra trước khi triển khai rộng." },
      ],
    },
  },
  {
    moduleSlug: "phoi-hop-va-giai-quyet-cong-viec",
    slug: "kiem-tra-phoi-hop-cong-viec",
    title: "Kiểm tra: Phối hợp công việc",
    summary: "Xử lý một tình huống tổng hợp gồm thay đổi ưu tiên, trễ hạn và phối hợp giữa nhiều người.",
    situation: "Thực hành cuối module 2",
    estimatedMinutes: 15,
    isFree: false,
    vocabulary: [
      word("xietiao", "协调", "xiétiáo", "điều phối", "我来协调两个部门的时间。", "Tôi sẽ điều phối thời gian của hai bộ phận."),
      word("gongshi", "共识", "gòngshí", "đồng thuận", "大家对新计划达成了共识。", "Mọi người đã đạt đồng thuận về kế hoạch mới."),
      word("chongtu", "冲突", "chōngtū", "xung đột", "两个任务的时间有冲突。", "Thời gian của hai nhiệm vụ bị xung đột."),
      word("jiejue-fangan", "解决方案", "jiějué fāng'àn", "phương án giải quyết", "我们需要一个可行的解决方案。", "Chúng ta cần một phương án giải quyết khả thi."),
      word("genjin", "跟进", "gēnjìn", "theo dõi tiếp", "我明天会跟进处理结果。", "Ngày mai tôi sẽ theo dõi kết quả xử lý."),
      word("queren-jieguo", "确认结果", "quèrèn jiéguǒ", "xác nhận kết quả", "完成后请确认结果。", "Sau khi hoàn thành hãy xác nhận kết quả."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "两个紧急任务的时间有冲突。", pinyin: "Liǎng ge jǐnjí rènwu de shíjiān yǒu chōngtū.", translation: "Thời gian của hai nhiệm vụ khẩn bị xung đột." },
        { speaker: "B", hanzi: "我来协调负责人，重新确认优先级。", pinyin: "Wǒ lái xiétiáo fùzérén, chóngxīn quèrèn yōuxiānjí.", translation: "Tôi sẽ điều phối người phụ trách và xác nhận lại mức ưu tiên." },
        { speaker: "A", hanzi: "请今天给出一个可行的解决方案。", pinyin: "Qǐng jīntiān gěichū yí ge kěxíng de jiějué fāng'àn.", translation: "Hãy đưa ra một phương án khả thi trong hôm nay." },
        { speaker: "B", hanzi: "好的，我会跟进并确认结果。", pinyin: "Hǎo de, wǒ huì gēnjìn bìng quèrèn jiéguǒ.", translation: "Vâng, tôi sẽ theo dõi và xác nhận kết quả." },
      ],
      notes: [
        { title: "Điều phối khi có xung đột", pattern: "我来协调……", explanation: "我来 thể hiện bạn chủ động nhận trách nhiệm điều phối, sau đó cần nói rõ người hoặc nguồn lực liên quan." },
        { title: "Chốt vòng phối hợp", pattern: "跟进并确认结果", explanation: "跟进 là theo dõi tiếp, còn 确认结果 đóng vòng công việc bằng một kết quả đã được xác nhận." },
      ],
      challenge: {
        title: "Bài kiểm tra phối hợp công việc",
        description: "Chọn cách phản hồi phù hợp trong các tình huống thay đổi và phối hợp.",
        passScore: 3,
        questions: [
          { prompt: "Quản lý giao thêm việc khẩn. Bạn nên làm gì trước?", options: ["Tự bỏ việc cũ", "Xác nhận lại mức ưu tiên và ảnh hưởng", "Từ chối ngay"], correctOption: 1, explanation: "Cần xác nhận ưu tiên và tác động trước khi thay đổi kế hoạch." },
          { prompt: "Câu nào báo trễ có trách nhiệm nhất?", options: ["我做不完。", "因为数据有问题，预计明天下午完成。", "以后再说。"], correctOption: 1, explanation: "Câu này có nguyên nhân và thời gian dự kiến mới." },
          { prompt: "Cụm nào dùng để nói hai lịch bị xung đột?", options: ["时间有冲突", "已经达成共识", "请查看附件"], correctOption: 0, explanation: "时间有冲突 nghĩa là thời gian bị trùng hoặc xung đột." },
          { prompt: "Sau khi đưa phương án, hành động nào giúp đóng vòng công việc?", options: ["等待别人提醒", "跟进并确认结果", "删除原来的资料"], correctOption: 1, explanation: "Theo dõi tiếp và xác nhận kết quả giúp tránh công việc bị bỏ lửng." },
        ],
      },
    },
  },
  {
    moduleSlug: "hop-bao-cao-va-du-an",
    slug: "chuan-bi-cuoc-hop",
    title: "Chuẩn bị cuộc họp",
    summary: "Xác định mục tiêu, người tham gia, chương trình và tài liệu cần gửi trước cuộc họp.",
    situation: "Chuẩn bị họp dự án",
    estimatedMinutes: 12,
    isFree: false,
    vocabulary: [
      word("yicheng", "议程", "yìchéng", "chương trình họp", "我已经更新了会议议程。", "Tôi đã cập nhật chương trình cuộc họp."),
      word("canhui-renyuan", "参会人员", "cānhuì rényuán", "người tham dự", "请确认参会人员名单。", "Vui lòng xác nhận danh sách người tham dự."),
      word("huiyi-cailiao", "会议材料", "huìyì cáiliào", "tài liệu họp", "会议材料会提前发送。", "Tài liệu họp sẽ được gửi trước."),
      word("mubiao", "目标", "mùbiāo", "mục tiêu", "这次会议的目标是什么？", "Mục tiêu của cuộc họp lần này là gì?"),
      word("tiqian", "提前", "tíqián", "trước, sớm hơn", "请提前十分钟到会议室。", "Vui lòng đến phòng họp trước mười phút."),
      word("zhunbei", "准备", "zhǔnbèi", "chuẩn bị", "我正在准备汇报材料。", "Tôi đang chuẩn bị tài liệu báo cáo."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "明天的项目会议准备得怎么样了？", pinyin: "Míngtiān de xiàngmù huìyì zhǔnbèi de zěnmeyàng le?", translation: "Cuộc họp dự án ngày mai chuẩn bị đến đâu rồi?" },
        { speaker: "B", hanzi: "议程和参会人员已经确认了。", pinyin: "Yìchéng hé cānhuì rényuán yǐjīng quèrèn le.", translation: "Chương trình và người tham dự đã được xác nhận." },
        { speaker: "A", hanzi: "会议材料今天可以发送吗？", pinyin: "Huìyì cáiliào jīntiān kěyǐ fāsòng ma?", translation: "Hôm nay có thể gửi tài liệu họp không?" },
        { speaker: "B", hanzi: "可以，我会提前发给大家。", pinyin: "Kěyǐ, wǒ huì tíqián fā gěi dàjiā.", translation: "Được, tôi sẽ gửi trước cho mọi người." },
      ],
      notes: [
        { title: "Kiểm tra mức độ chuẩn bị", pattern: "准备得怎么样了？", explanation: "得怎么样 dùng để hỏi mức độ hoặc chất lượng thực hiện của một hành động." },
        { title: "Thông báo gửi trước", pattern: "会提前发给大家", explanation: "提前 cho biết hành động sẽ diễn ra trước mốc cần thiết, giúp người tham dự có thời gian đọc tài liệu." },
      ],
    },
  },
  {
    moduleSlug: "hop-bao-cao-va-du-an",
    slug: "phat-bieu-y-kien-trong-cuoc-hop",
    title: "Phát biểu ý kiến trong cuộc họp",
    summary: "Đồng ý, không đồng ý và bổ sung quan điểm mà vẫn giữ thái độ hợp tác.",
    situation: "Thảo luận phương án",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("yijian", "意见", "yìjiàn", "ý kiến", "我想听听大家的意见。", "Tôi muốn nghe ý kiến của mọi người."),
      word("tongyi", "同意", "tóngyì", "đồng ý", "我同意这个安排。", "Tôi đồng ý với sắp xếp này."),
      word("bu-tongyi", "不同意", "bù tóngyì", "không đồng ý", "我不完全同意这个观点。", "Tôi không hoàn toàn đồng ý với quan điểm này."),
      word("buchong", "补充", "bǔchōng", "bổ sung", "我想补充一点。", "Tôi muốn bổ sung một điểm."),
      word("guandian", "观点", "guāndiǎn", "quan điểm", "这个观点很有参考价值。", "Quan điểm này rất đáng tham khảo."),
      word("kaolv", "考虑", "kǎolǜ", "cân nhắc", "我们还需要考虑成本。", "Chúng ta còn cần cân nhắc chi phí."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "大家对这个方案有什么意见？", pinyin: "Dàjiā duì zhège fāng'àn yǒu shénme yìjiàn?", translation: "Mọi người có ý kiến gì về phương án này?" },
        { speaker: "B", hanzi: "我基本同意，不过还需要考虑成本。", pinyin: "Wǒ jīběn tóngyì, búguò hái xūyào kǎolǜ chéngběn.", translation: "Tôi cơ bản đồng ý, nhưng vẫn cần cân nhắc chi phí." },
        { speaker: "C", hanzi: "我想补充一点，时间也比较紧。", pinyin: "Wǒ xiǎng bǔchōng yìdiǎn, shíjiān yě bǐjiào jǐn.", translation: "Tôi muốn bổ sung một điểm: thời gian cũng khá gấp." },
        { speaker: "A", hanzi: "好的，我们把这两个问题一起讨论。", pinyin: "Hǎo de, wǒmen bǎ zhè liǎng ge wèntí yìqǐ tǎolùn.", translation: "Được, chúng ta sẽ thảo luận hai vấn đề này cùng nhau." },
      ],
      notes: [
        { title: "Không đồng ý mềm", pattern: "我基本同意，不过……", explanation: "Thừa nhận phần bạn đồng ý trước, sau đó dùng 不过 để nêu điểm còn băn khoăn." },
        { title: "Xin bổ sung", pattern: "我想补充一点", explanation: "Mẫu mở lời ngắn và lịch sự để thêm thông tin mà không ngắt mạch cuộc họp quá mạnh." },
      ],
    },
  },
  {
    moduleSlug: "hop-bao-cao-va-du-an",
    slug: "ghi-nhan-quyet-dinh-va-hanh-dong",
    title: "Ghi nhận quyết định và hành động",
    summary: "Chốt kết luận, người phụ trách, thời hạn và các việc cần làm sau cuộc họp.",
    situation: "Kết thúc cuộc họp",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("jueding", "决定", "juédìng", "quyết định", "会议决定下周开始测试。", "Cuộc họp quyết định bắt đầu thử nghiệm vào tuần sau."),
      word("jielun", "结论", "jiélùn", "kết luận", "请把会议结论写清楚。", "Vui lòng ghi rõ kết luận cuộc họp."),
      word("huiyi-jilu", "会议记录", "huìyì jìlù", "biên bản họp", "我会整理会议记录。", "Tôi sẽ tổng hợp biên bản họp."),
      word("xingdong-xiang", "行动项", "xíngdòng xiàng", "hạng mục hành động", "每个行动项都要有负责人。", "Mỗi hạng mục hành động đều phải có người phụ trách."),
      word("fengong", "分工", "fēngōng", "phân công", "项目分工已经确认。", "Phân công dự án đã được xác nhận."),
      word("qixian", "期限", "qīxiàn", "thời hạn", "这个行动项的期限是周五。", "Thời hạn của hạng mục này là thứ Sáu."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "今天的会议结论是什么？", pinyin: "Jīntiān de huìyì jiélùn shì shénme?", translation: "Kết luận cuộc họp hôm nay là gì?" },
        { speaker: "B", hanzi: "我们决定下周开始小范围测试。", pinyin: "Wǒmen juédìng xià zhōu kāishǐ xiǎo fànwéi cèshì.", translation: "Chúng ta quyết định bắt đầu thử nghiệm quy mô nhỏ tuần sau." },
        { speaker: "A", hanzi: "请确认行动项、负责人和期限。", pinyin: "Qǐng quèrèn xíngdòng xiàng, fùzérén hé qīxiàn.", translation: "Hãy xác nhận hạng mục hành động, người phụ trách và thời hạn." },
        { speaker: "B", hanzi: "好的，我会写进会议记录并发给大家。", pinyin: "Hǎo de, wǒ huì xiě jìn huìyì jìlù bìng fā gěi dàjiā.", translation: "Vâng, tôi sẽ ghi vào biên bản và gửi cho mọi người." },
      ],
      notes: [
        { title: "Chốt ba thông tin", pattern: "行动项、负责人和期限", explanation: "Ba thành phần này giúp quyết định trong cuộc họp trở thành công việc có thể theo dõi." },
        { title: "Ghi vào biên bản", pattern: "写进会议记录", explanation: "进 sau động từ nhấn mạnh đưa thông tin vào một tài liệu hoặc hệ thống cụ thể." },
      ],
    },
  },
  {
    moduleSlug: "hop-bao-cao-va-du-an",
    slug: "bao-cao-so-lieu-va-xu-huong",
    title: "Báo cáo số liệu và xu hướng",
    summary: "Mô tả tăng giảm, tỷ trọng và xu hướng chính mà không chỉ đọc lại từng con số.",
    situation: "Trình bày báo cáo tháng",
    estimatedMinutes: 14,
    isFree: false,
    vocabulary: [
      word("tongbi", "同比", "tóngbǐ", "so với cùng kỳ", "销售额同比增长了百分之十。", "Doanh số tăng 10% so với cùng kỳ."),
      word("huanbi", "环比", "huánbǐ", "so với kỳ liền trước", "本月订单量环比下降。", "Số đơn tháng này giảm so với tháng trước."),
      word("zengzhang", "增长", "zēngzhǎng", "tăng trưởng", "线上销售保持增长。", "Bán hàng trực tuyến duy trì tăng trưởng."),
      word("xiajiang", "下降", "xiàjiàng", "giảm", "客户投诉数量明显下降。", "Số lượng khiếu nại của khách giảm rõ rệt."),
      word("zhanbi", "占比", "zhànbǐ", "tỷ trọng", "新客户的占比是百分之三十。", "Khách hàng mới chiếm tỷ trọng 30%."),
      word("qushi", "趋势", "qūshì", "xu hướng", "整体趋势比较稳定。", "Xu hướng tổng thể khá ổn định."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "请介绍一下本月的主要数据。", pinyin: "Qǐng jièshào yíxià běn yuè de zhǔyào shùjù.", translation: "Hãy giới thiệu các số liệu chính của tháng này." },
        { speaker: "B", hanzi: "销售额同比增长了百分之十。", pinyin: "Xiāoshòu'é tóngbǐ zēngzhǎng le bǎifēnzhī shí.", translation: "Doanh số tăng 10% so với cùng kỳ." },
        { speaker: "A", hanzi: "订单量的趋势怎么样？", pinyin: "Dìngdān liàng de qūshì zěnmeyàng?", translation: "Xu hướng số lượng đơn hàng thế nào?" },
        { speaker: "B", hanzi: "整体比较稳定，不过线下订单环比有所下降。", pinyin: "Zhěngtǐ bǐjiào wěndìng, búguò xiànxià dìngdān huánbǐ yǒusuǒ xiàjiàng.", translation: "Tổng thể khá ổn định, nhưng đơn hàng ngoại tuyến giảm nhẹ so với kỳ trước." },
      ],
      notes: [
        { title: "Phân biệt hai kiểu so sánh", pattern: "同比 / 环比", explanation: "同比 so với cùng kỳ năm trước; 环比 so với kỳ ngay trước đó. Nên ghi rõ mốc nếu người nghe chưa quen." },
        { title: "Mô tả giảm nhẹ", pattern: "有所下降", explanation: "有所 làm mức thay đổi nghe trung tính hơn, phù hợp khi mức giảm không quá lớn." },
      ],
    },
  },
  {
    moduleSlug: "hop-bao-cao-va-du-an",
    slug: "quan-ly-rui-ro-du-an",
    title: "Quản lý rủi ro dự án",
    summary: "Nêu trở ngại, phụ thuộc, phương án dự phòng và trường hợp cần báo cáo lên cấp trên.",
    situation: "Rà soát rủi ro hằng tuần",
    estimatedMinutes: 14,
    isFree: false,
    vocabulary: [
      word("zhangai", "障碍", "zhàng'ài", "trở ngại", "目前最大的障碍是人手不足。", "Trở ngại lớn nhất hiện tại là thiếu nhân lực."),
      word("yilai", "依赖", "yīlài", "sự phụ thuộc", "这个任务依赖技术部门的支持。", "Nhiệm vụ này phụ thuộc vào hỗ trợ của bộ phận kỹ thuật."),
      word("yufang", "预防", "yùfáng", "phòng ngừa", "我们需要提前预防这个问题。", "Chúng ta cần phòng ngừa vấn đề này từ sớm."),
      word("yingdui", "应对", "yìngduì", "ứng phó", "团队已经准备好应对变化。", "Nhóm đã sẵn sàng ứng phó thay đổi."),
      word("beiyong-fangan", "备用方案", "bèiyòng fāng'àn", "phương án dự phòng", "如果系统失败，我们有备用方案。", "Nếu hệ thống gặp lỗi, chúng ta có phương án dự phòng."),
      word("shangbao", "上报", "shàngbào", "báo cáo lên cấp trên", "严重问题要及时上报。", "Vấn đề nghiêm trọng cần được báo cáo kịp thời."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "项目目前有什么主要障碍？", pinyin: "Xiàngmù mùqián yǒu shénme zhǔyào zhàng'ài?", translation: "Dự án hiện có trở ngại chính nào?" },
        { speaker: "B", hanzi: "测试任务依赖技术部门的支持。", pinyin: "Cèshì rènwu yīlài jìshù bùmén de zhīchí.", translation: "Nhiệm vụ kiểm thử phụ thuộc vào hỗ trợ của bộ phận kỹ thuật." },
        { speaker: "A", hanzi: "如果他们不能按时完成，我们怎么应对？", pinyin: "Rúguǒ tāmen bù néng ànshí wánchéng, wǒmen zěnme yìngduì?", translation: "Nếu họ không hoàn thành đúng hạn, chúng ta ứng phó thế nào?" },
        { speaker: "B", hanzi: "我们有备用方案，严重问题会及时上报。", pinyin: "Wǒmen yǒu bèiyòng fāng'àn, yánzhòng wèntí huì jíshí shàngbào.", translation: "Chúng ta có phương án dự phòng; vấn đề nghiêm trọng sẽ được báo cáo kịp thời." },
      ],
      notes: [
        { title: "Nêu sự phụ thuộc", pattern: "……依赖……的支持", explanation: "Mẫu này giúp chỉ rõ bên nào hoặc điều kiện nào đang ảnh hưởng khả năng hoàn thành." },
        { title: "Đặt tình huống rủi ro", pattern: "如果……，我们怎么应对？", explanation: "Nếu nêu một rủi ro, nên nối ngay bằng câu hỏi về cách ứng phó hoặc phương án dự phòng." },
      ],
    },
  },
  {
    moduleSlug: "hop-bao-cao-va-du-an",
    slug: "kiem-tra-hop-bao-cao-du-an",
    title: "Kiểm tra: Họp, báo cáo & dự án",
    summary: "Thực hành chuẩn bị họp, trình bày xu hướng và chốt trách nhiệm sau cuộc họp.",
    situation: "Thực hành cuối module 3",
    estimatedMinutes: 16,
    isFree: false,
    vocabulary: [
      word("zhuchi", "主持", "zhǔchí", "chủ trì", "今天的会议由王经理主持。", "Cuộc họp hôm nay do quản lý Vương chủ trì."),
      word("huizong", "汇总", "huìzǒng", "tổng hợp", "请汇总各部门的数据。", "Vui lòng tổng hợp dữ liệu của các bộ phận."),
      word("zhongdian", "重点", "zhòngdiǎn", "trọng điểm", "汇报时请说明三个重点。", "Khi báo cáo hãy trình bày ba trọng điểm."),
      word("xiayibu", "下一步", "xià yí bù", "bước tiếp theo", "下一步是安排客户测试。", "Bước tiếp theo là sắp xếp thử nghiệm với khách hàng."),
      word("zerenren", "责任人", "zérènrén", "người chịu trách nhiệm", "每个任务都要确认责任人。", "Mỗi nhiệm vụ đều phải xác nhận người chịu trách nhiệm."),
      word("wancheng-shijian", "完成时间", "wánchéng shíjiān", "thời gian hoàn thành", "请确认预计完成时间。", "Vui lòng xác nhận thời gian dự kiến hoàn thành."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "请先汇总数据，再说明三个重点。", pinyin: "Qǐng xiān huìzǒng shùjù, zài shuōmíng sān ge zhòngdiǎn.", translation: "Hãy tổng hợp dữ liệu trước, sau đó trình bày ba trọng điểm." },
        { speaker: "B", hanzi: "好的，我也会准备风险和备用方案。", pinyin: "Hǎo de, wǒ yě huì zhǔnbèi fēngxiǎn hé bèiyòng fāng'àn.", translation: "Vâng, tôi cũng sẽ chuẩn bị phần rủi ro và phương án dự phòng." },
        { speaker: "A", hanzi: "会议结束前要确认下一步和责任人。", pinyin: "Huìyì jiéshù qián yào quèrèn xià yí bù hé zérènrén.", translation: "Trước khi kết thúc họp cần xác nhận bước tiếp theo và người chịu trách nhiệm." },
        { speaker: "B", hanzi: "明白，我会记录预计完成时间。", pinyin: "Míngbai, wǒ huì jìlù yùjì wánchéng shíjiān.", translation: "Tôi hiểu, tôi sẽ ghi lại thời gian dự kiến hoàn thành." },
      ],
      notes: [
        { title: "Trình bày có cấu trúc", pattern: "先……，再……", explanation: "先…再… giúp người nghe theo dõi thứ tự các phần trong một bài báo cáo." },
        { title: "Chốt trước khi kết thúc", pattern: "结束前要确认……", explanation: "Mẫu nhắc việc phải hoàn tất trước một mốc; ở đây là bước tiếp theo, người chịu trách nhiệm và thời gian." },
      ],
      challenge: {
        title: "Bài kiểm tra họp và dự án",
        description: "Kiểm tra khả năng chuẩn bị, trình bày và chốt việc sau cuộc họp.",
        passScore: 3,
        questions: [
          { prompt: "Tài liệu họp nên được gửi khi nào?", options: ["Sau cuộc họp", "提前发送", "Chỉ khi có người hỏi"], correctOption: 1, explanation: "提前发送 cho người tham dự thời gian đọc trước." },
          { prompt: "Cách nào không đồng ý mềm và hợp tác?", options: ["你错了。", "我基本同意，不过还需要考虑成本。", "这个方案不能用。"], correctOption: 1, explanation: "Câu này thừa nhận điểm đồng thuận rồi mới nêu điều cần cân nhắc." },
          { prompt: "Ba thông tin cần chốt sau họp là gì?", options: ["行动项、负责人和期限", "标题、颜色和字体", "姓名、年龄和地址"], correctOption: 0, explanation: "Đây là ba thành phần biến quyết định thành hành động theo dõi được." },
          { prompt: "Nếu nhiệm vụ phụ thuộc bộ phận khác, bạn nên làm rõ điều gì?", options: ["Sở thích của họ", "Sự phụ thuộc và phương án dự phòng", "Chỉ chờ đến hạn"], correctOption: 1, explanation: "Làm rõ phụ thuộc và dự phòng giúp quản lý rủi ro trước khi trễ." },
        ],
      },
    },
  },
  {
    moduleSlug: "hanh-chinh-va-giao-tiep-nang-cao",
    slug: "xin-nghi-va-bao-di-muon",
    title: "Xin nghỉ và báo đi muộn",
    summary: "Thông báo lý do, thời gian vắng mặt và cách bàn giao để không ảnh hưởng công việc chung.",
    situation: "Thông báo thay đổi giờ làm",
    estimatedMinutes: 12,
    isFree: false,
    vocabulary: [
      word("qingjia", "请假", "qǐngjià", "xin nghỉ", "我想请一天假。", "Tôi muốn xin nghỉ một ngày."),
      word("chidao", "迟到", "chídào", "đi muộn", "今天路上堵车，我会迟到。", "Hôm nay đường tắc nên tôi sẽ đến muộn."),
      word("bingjia", "病假", "bìngjià", "nghỉ ốm", "他今天请病假。", "Hôm nay anh ấy nghỉ ốm."),
      word("shijia", "事假", "shìjià", "nghỉ việc riêng", "我需要请半天事假。", "Tôi cần xin nghỉ việc riêng nửa ngày."),
      word("pizhun", "批准", "pīzhǔn", "phê duyệt", "请假申请已经批准了。", "Đơn xin nghỉ đã được phê duyệt."),
      word("kaoqin", "考勤", "kǎoqín", "chấm công", "请在系统里更新考勤。", "Vui lòng cập nhật chấm công trong hệ thống."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "经理，不好意思，我明天想请一天病假。", pinyin: "Jīnglǐ, bù hǎoyìsi, wǒ míngtiān xiǎng qǐng yì tiān bìngjià.", translation: "Quản lý, xin lỗi, ngày mai tôi muốn xin nghỉ ốm một ngày." },
        { speaker: "B", hanzi: "好的，手上的工作安排好了吗？", pinyin: "Hǎo de, shǒushàng de gōngzuò ānpái hǎo le ma?", translation: "Được, công việc đang phụ trách đã sắp xếp ổn chưa?" },
        { speaker: "A", hanzi: "已经交接给小李了，我也会更新考勤。", pinyin: "Yǐjīng jiāojiē gěi Xiǎo Lǐ le, wǒ yě huì gēngxīn kǎoqín.", translation: "Tôi đã bàn giao cho Tiểu Lý và cũng sẽ cập nhật chấm công." },
        { speaker: "B", hanzi: "可以，申请批准以后好好休息。", pinyin: "Kěyǐ, shēnqǐng pīzhǔn yǐhòu hǎohāo xiūxi.", translation: "Được, sau khi đơn được duyệt thì hãy nghỉ ngơi cho tốt." },
      ],
      notes: [
        { title: "Nói rõ loại nghỉ", pattern: "请一天病假 / 请半天事假", explanation: "Nói rõ loại nghỉ và thời lượng giúp người quản lý xử lý chấm công và sắp xếp thay thế." },
        { title: "Chủ động bàn giao", pattern: "已经交接给……了", explanation: "Khi xin nghỉ, cho biết công việc đã được bàn giao sẽ tạo cảm giác đáng tin cậy và giảm câu hỏi tiếp theo." },
      ],
    },
  },
  {
    moduleSlug: "hanh-chinh-va-giao-tiep-nang-cao",
    slug: "xu-ly-quy-trinh-phe-duyet",
    title: "Xử lý quy trình phê duyệt",
    summary: "Hỏi đúng bước, chuẩn bị biểu mẫu và theo dõi hồ sơ đang chờ ký hoặc đóng dấu.",
    situation: "Nộp đề nghị mua hàng",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("shenpi", "审批", "shěnpī", "phê duyệt", "这份申请正在审批中。", "Đơn này đang trong quá trình phê duyệt."),
      word("shenqing", "申请", "shēnqǐng", "đề nghị, đơn đăng ký", "请先提交采购申请。", "Vui lòng nộp đề nghị mua hàng trước."),
      word("biaoge", "表格", "biǎogé", "biểu mẫu", "这个表格需要填写完整。", "Biểu mẫu này cần được điền đầy đủ."),
      word("qianzi", "签字", "qiānzì", "ký tên", "请负责人在这里签字。", "Vui lòng để người phụ trách ký tại đây."),
      word("gaizhang", "盖章", "gàizhāng", "đóng dấu", "合同签字后还需要盖章。", "Hợp đồng sau khi ký còn cần đóng dấu."),
      word("liucheng", "流程", "liúchéng", "quy trình", "我不太清楚报销流程。", "Tôi chưa rõ quy trình hoàn ứng."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "我想提交采购申请，请问流程是什么？", pinyin: "Wǒ xiǎng tíjiāo cǎigòu shēnqǐng, qǐngwèn liúchéng shì shénme?", translation: "Tôi muốn nộp đề nghị mua hàng, xin hỏi quy trình thế nào?" },
        { speaker: "B", hanzi: "先填写表格，再请部门负责人签字。", pinyin: "Xiān tiánxiě biǎogé, zài qǐng bùmén fùzérén qiānzì.", translation: "Trước tiên điền biểu mẫu, sau đó xin người phụ trách bộ phận ký." },
        { speaker: "A", hanzi: "签字以后需要盖章吗？", pinyin: "Qiānzì yǐhòu xūyào gàizhāng ma?", translation: "Sau khi ký có cần đóng dấu không?" },
        { speaker: "B", hanzi: "这类申请不需要，直接进入审批流程。", pinyin: "Zhè lèi shēnqǐng bù xūyào, zhíjiē jìnrù shěnpī liúchéng.", translation: "Loại đề nghị này không cần, sẽ đi thẳng vào quy trình phê duyệt." },
      ],
      notes: [
        { title: "Hỏi quy trình", pattern: "请问流程是什么？", explanation: "Dùng khi bạn biết mục tiêu nhưng chưa rõ thứ tự các bước hoặc người cần phê duyệt." },
        { title: "Mô tả thứ tự", pattern: "先……，再……", explanation: "Mẫu quen thuộc để hướng dẫn một quy trình ngắn gồm các bước tuần tự." },
      ],
    },
  },
  {
    moduleSlug: "hanh-chinh-va-giao-tiep-nang-cao",
    slug: "don-tiep-doi-tac-va-khach-den",
    title: "Đón tiếp đối tác và khách đến",
    summary: "Xác nhận lịch hẹn, hướng dẫn đăng ký và đưa khách đến đúng người phụ trách.",
    situation: "Khách đến văn phòng",
    estimatedMinutes: 12,
    isFree: false,
    vocabulary: [
      word("jiedai", "接待", "jiēdài", "đón tiếp", "今天由我负责接待客户。", "Hôm nay tôi phụ trách đón tiếp khách hàng."),
      word("laifang", "来访", "láifǎng", "đến thăm, ghé làm việc", "感谢您来访我们公司。", "Cảm ơn anh/chị đã đến thăm công ty chúng tôi."),
      word("qiantai", "前台", "qiántái", "quầy lễ tân", "请先到前台登记。", "Vui lòng đăng ký tại quầy lễ tân trước."),
      word("yuyue", "预约", "yùyuē", "đặt hẹn", "请问您有预约吗？", "Xin hỏi anh/chị có lịch hẹn không?"),
      word("fangke", "访客", "fǎngkè", "khách đến làm việc", "访客需要佩戴临时证件。", "Khách cần đeo thẻ tạm thời."),
      word("yindao", "引导", "yǐndǎo", "hướng dẫn, dẫn đường", "我来引导您去会议室。", "Tôi sẽ dẫn anh/chị đến phòng họp."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "您好，请问您有预约吗？", pinyin: "Nín hǎo, qǐngwèn nín yǒu yùyuē ma?", translation: "Xin chào, xin hỏi anh/chị có lịch hẹn không?" },
        { speaker: "B", hanzi: "有，我和销售部的陈经理约了十点。", pinyin: "Yǒu, wǒ hé xiāoshòubù de Chén jīnglǐ yuē le shí diǎn.", translation: "Có, tôi hẹn quản lý Trần của bộ phận kinh doanh lúc 10 giờ." },
        { speaker: "A", hanzi: "好的，请先在前台登记。", pinyin: "Hǎo de, qǐng xiān zài qiántái dēngjì.", translation: "Vâng, vui lòng đăng ký tại lễ tân trước." },
        { speaker: "A", hanzi: "登记后我带您去会议室。", pinyin: "Dēngjì hòu wǒ dài nín qù huìyìshì.", translation: "Sau khi đăng ký, tôi sẽ đưa anh/chị đến phòng họp." },
      ],
      notes: [
        { title: "Xác nhận lịch hẹn", pattern: "请问您有预约吗？", explanation: "Dùng 您 để giữ mức lịch sự khi tiếp khách; sau đó hỏi tên người hoặc bộ phận được hẹn." },
        { title: "Hướng dẫn bước tiếp theo", pattern: "请先……，登记后……", explanation: "Nêu từng bước giúp khách biết phải làm gì trước khi được dẫn vào khu vực làm việc." },
      ],
    },
  },
  {
    moduleSlug: "hanh-chinh-va-giao-tiep-nang-cao",
    slug: "giao-tiep-qua-dien-thoai",
    title: "Giao tiếp qua điện thoại",
    summary: "Xác nhận người gọi, chuyển máy, ghi lời nhắn và xử lý khi đường dây đang bận.",
    situation: "Nhận cuộc gọi cho đồng nghiệp",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("jie-dianhua", "接电话", "jiē diànhuà", "nghe điện thoại", "现在方便接电话吗？", "Bây giờ có tiện nghe điện thoại không?"),
      word("zhuanjie", "转接", "zhuǎnjiē", "chuyển máy", "我帮您转接销售部。", "Tôi sẽ chuyển máy cho anh/chị sang bộ phận kinh doanh."),
      word("fenji", "分机", "fēnjī", "số máy lẻ", "他的分机号码是八零六。", "Số máy lẻ của anh ấy là 806."),
      word("liuyan", "留言", "liúyán", "để lại lời nhắn", "您需要留言吗？", "Anh/chị có cần để lại lời nhắn không?"),
      word("shaodeng", "稍等", "shāoděng", "chờ một chút", "请稍等，我帮您查询。", "Vui lòng chờ một chút, tôi sẽ kiểm tra giúp."),
      word("zhanxian", "占线", "zhànxiàn", "máy bận", "经理的电话现在占线。", "Điện thoại của quản lý hiện đang bận."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "您好，这里是汉字公司。请问您找哪位？", pinyin: "Nín hǎo, zhèlǐ shì Hànzì gōngsī. Qǐngwèn nín zhǎo nǎ wèi?", translation: "Xin chào, đây là công ty Hanzi. Xin hỏi anh/chị tìm ai?" },
        { speaker: "B", hanzi: "我找销售部的王经理。", pinyin: "Wǒ zhǎo xiāoshòubù de Wáng jīnglǐ.", translation: "Tôi tìm quản lý Vương của bộ phận kinh doanh." },
        { speaker: "A", hanzi: "请稍等，他的电话现在占线。", pinyin: "Qǐng shāoděng, tā de diànhuà xiànzài zhànxiàn.", translation: "Vui lòng chờ một chút, điện thoại của anh ấy hiện đang bận." },
        { speaker: "A", hanzi: "您需要留言，还是稍后再打来？", pinyin: "Nín xūyào liúyán, háishì shāohòu zài dǎ lái?", translation: "Anh/chị muốn để lại lời nhắn hay gọi lại sau?" },
      ],
      notes: [
        { title: "Hỏi người cần gặp", pattern: "请问您找哪位？", explanation: "哪位 là cách hỏi lịch sự hơn 谁 trong giao tiếp qua điện thoại hoặc lễ tân." },
        { title: "Đưa hai lựa chọn", pattern: "您需要……，还是……？", explanation: "还是 nối hai lựa chọn trong câu hỏi, giúp người gọi quyết định để lại lời nhắn hay gọi lại." },
      ],
    },
  },
  {
    moduleSlug: "hanh-chinh-va-giao-tiep-nang-cao",
    slug: "xu-ly-hieu-lam-trong-cong-viec",
    title: "Xử lý hiểu lầm trong công việc",
    summary: "Làm rõ điều đã nghe, xin lỗi khi cần và xác nhận lại để tránh lặp lại hiểu lầm.",
    situation: "Hai bên hiểu khác một yêu cầu",
    estimatedMinutes: 13,
    isFree: false,
    vocabulary: [
      word("wuhui", "误会", "wùhuì", "hiểu lầm", "这可能是一个误会。", "Đây có thể là một hiểu lầm."),
      word("chengqing", "澄清", "chéngqīng", "làm rõ", "我想澄清一下刚才的要求。", "Tôi muốn làm rõ yêu cầu lúc nãy."),
      word("biaoda", "表达", "biǎodá", "diễn đạt", "可能是我表达得不够清楚。", "Có thể tôi diễn đạt chưa đủ rõ."),
      word("lijie", "理解", "lǐjiě", "hiểu", "我理解的意思不太一样。", "Cách tôi hiểu hơi khác."),
      word("baoqian", "抱歉", "bàoqiàn", "xin lỗi", "很抱歉给您带来不便。", "Rất xin lỗi vì đã gây bất tiện cho anh/chị."),
      word("zai-queren", "再确认", "zài quèrèn", "xác nhận lại", "我们把要求再确认一次。", "Chúng ta hãy xác nhận lại yêu cầu một lần nữa."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "为什么你把所有文件都发给客户了？", pinyin: "Wèishénme nǐ bǎ suǒyǒu wénjiàn dōu fā gěi kèhù le?", translation: "Tại sao bạn gửi toàn bộ tài liệu cho khách hàng?" },
        { speaker: "B", hanzi: "抱歉，我理解的是需要发送全部文件。", pinyin: "Bàoqiàn, wǒ lǐjiě de shì xūyào fāsòng quánbù wénjiàn.", translation: "Xin lỗi, tôi hiểu là cần gửi toàn bộ tài liệu." },
        { speaker: "A", hanzi: "可能是我表达得不够清楚。", pinyin: "Kěnéng shì wǒ biǎodá de bú gòu qīngchu.", translation: "Có thể tôi diễn đạt chưa đủ rõ." },
        { speaker: "B", hanzi: "我们把要求再确认一次，避免再次误会。", pinyin: "Wǒmen bǎ yāoqiú zài quèrèn yí cì, bìmiǎn zàicì wùhuì.", translation: "Chúng ta hãy xác nhận lại yêu cầu để tránh hiểu lầm lần nữa." },
      ],
      notes: [
        { title: "Làm dịu tình huống", pattern: "可能是我表达得不够清楚", explanation: "Nhận một phần trách nhiệm về cách diễn đạt giúp chuyển cuộc trao đổi từ đổ lỗi sang giải quyết." },
        { title: "Xác nhận lại", pattern: "把要求再确认一次", explanation: "把 đưa 要求 lên trước hành động 确认, nhấn mạnh đối tượng cần xác nhận lại." },
      ],
    },
  },
  {
    moduleSlug: "hanh-chinh-va-giao-tiep-nang-cao",
    slug: "kiem-tra-tong-hop-van-phong",
    title: "Kiểm tra tổng hợp: Văn phòng & hành chính",
    summary: "Tổng hợp các kỹ năng nhận việc, phối hợp, họp, báo cáo và xử lý tình huống hành chính.",
    situation: "Bài kiểm tra cuối lộ trình",
    estimatedMinutes: 18,
    isFree: false,
    vocabulary: [
      word("qingjing", "情境", "qíngjìng", "tình huống, bối cảnh", "请根据工作情境选择表达。", "Hãy chọn cách diễn đạt dựa trên tình huống công việc."),
      word("goutong-mubiao", "沟通目标", "gōutōng mùbiāo", "mục tiêu giao tiếp", "先确认这次沟通的目标。", "Trước tiên xác nhận mục tiêu giao tiếp lần này."),
      word("guanjian-ju", "关键句", "guānjiàn jù", "câu then chốt", "请记住这个情境的关键句。", "Hãy nhớ câu then chốt của tình huống này."),
      word("deti", "得体", "détǐ", "phù hợp, đúng mực", "这种表达更礼貌得体。", "Cách diễn đạt này lịch sự và phù hợp hơn."),
      word("zonghe-zongjie", "总结", "zǒngjié", "tổng kết", "最后请总结下一步安排。", "Cuối cùng hãy tổng kết sắp xếp bước tiếp theo."),
      word("fupan", "复盘", "fùpán", "xem lại, rút kinh nghiệm", "项目结束后我们会进行复盘。", "Sau khi dự án kết thúc, chúng ta sẽ cùng xem lại và rút kinh nghiệm."),
    ],
    content: {
      dialogue: [
        { speaker: "A", hanzi: "请总结一下今天的问题和下一步安排。", pinyin: "Qǐng zǒngjié yíxià jīntiān de wèntí hé xià yí bù ānpái.", translation: "Hãy tổng kết vấn đề hôm nay và sắp xếp bước tiếp theo." },
        { speaker: "B", hanzi: "我们先澄清客户要求，再调整任务优先级。", pinyin: "Wǒmen xiān chéngqīng kèhù yāoqiú, zài tiáozhěng rènwu yōuxiānjí.", translation: "Chúng ta sẽ làm rõ yêu cầu khách hàng trước, rồi điều chỉnh ưu tiên nhiệm vụ." },
        { speaker: "A", hanzi: "请确认负责人和预计完成时间。", pinyin: "Qǐng quèrèn fùzérén hé yùjì wánchéng shíjiān.", translation: "Hãy xác nhận người phụ trách và thời gian dự kiến hoàn thành." },
        { speaker: "B", hanzi: "好的，项目结束后我们也会进行复盘。", pinyin: "Hǎo de, xiàngmù jiéshù hòu wǒmen yě huì jìnxíng fùpán.", translation: "Vâng, sau khi dự án kết thúc chúng ta cũng sẽ xem lại để rút kinh nghiệm." },
      ],
      notes: [
        { title: "Tổng kết hành động", pattern: "总结问题和下一步安排", explanation: "Một phần tổng kết tốt cần nêu vấn đề đã thống nhất và bước cụ thể tiếp theo." },
        { title: "Tạo thói quen xem lại", pattern: "结束后进行复盘", explanation: "复盘 không chỉ là kể lại; mục tiêu là tìm điều cần giữ, điều cần sửa và hành động cho lần sau." },
      ],
      challenge: {
        title: "Bài kiểm tra cuối lộ trình",
        description: "Hoàn thành 4/5 câu để kết thúc lộ trình Văn phòng & hành chính.",
        passScore: 4,
        questions: [
          { prompt: "Khi yêu cầu chưa rõ, hành động đầu tiên phù hợp là gì?", options: ["Bắt đầu theo suy đoán", "Hỏi cụ thể phạm vi và tiêu chuẩn", "Chuyển việc cho người khác"], correctOption: 1, explanation: "Làm rõ phạm vi và tiêu chuẩn giảm rủi ro phải làm lại." },
          { prompt: "Khi chắc chắn sẽ trễ, thông báo tốt cần có gì?", options: ["Chỉ nói xin lỗi", "Nguyên nhân, mốc dự kiến mới và phương án khắc phục", "Chờ đến khi bị hỏi"], correctOption: 1, explanation: "Ba phần này giúp người nhận đánh giá và điều chỉnh kế hoạch." },
          { prompt: "Sau cuộc họp, đâu là bộ thông tin cần xác nhận?", options: ["行动项、负责人和期限", "会议室、饮料和座位", "文件名、字体和颜色"], correctOption: 0, explanation: "Hạng mục hành động, người phụ trách và thời hạn giúp theo dõi quyết định." },
          { prompt: "Khi phát hiện hiểu lầm, câu nào hợp tác nhất?", options: ["你完全错了。", "可能是我表达得不够清楚，我们再确认一次。", "以后不要再问。"], correctOption: 1, explanation: "Câu này giảm đổ lỗi và đưa cuộc trao đổi về việc xác nhận lại." },
          { prompt: "VIP giữ chân người học tốt nhất bằng giá trị nào trong lộ trình này?", options: ["Chỉ khóa thêm bài", "Ôn từ yếu, kiểm tra module và thử thách mới", "Hiệu ứng chuyển động thật nhiều"], correctOption: 1, explanation: "Giá trị lặp lại và phản hồi cá nhân hóa mới tạo lý do quay lại." },
        ],
      },
    },
  },
];
